### ISSUE TITLE
Support for year parameter in crons

### ISSUE THREAD

**Issue by sirfuzzalot** [Sonic0/local-crontab#1]
AWS Event Bridge requires a year parameter. Would be great if this library could support that sixth parameter

https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-create-rule-schedule.html#eb-cron-expressions

Also, thanks for building this library 👍

**Comment by Sonic0** [comment]
Hey @sirfuzzalot, refer to the answer to your other issue.

**Comment by sirfuzzalot** [comment]
Resolved in other issue
