### ISSUE TITLE
Support for "L" "?" "#" characters in crons

### ISSUE THREAD

**Issue by sirfuzzalot** [Sonic0/local-crontab#2]
There are some cron systems that use these additional symbols. For example AWS Event Bridge / Cloud Watch Events.

https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-create-rule-schedule.html#eb-cron-expressions

Example
```
* 10 * * ? *
```

**Comment by sirfuzzalot** [comment]
Ok. narrowed it down, 😆 . Thanks for supporting the vast majority of characters already. The `?` is the big one I'm hitting issues with in `day of the week`.

**Comment by Sonic0** [comment]
Hey @sirfuzzalot, 
I made an "[Ansible plugin](https://github.com/Sonic0/local-crontab-ansible-filter/blob/main/filter_plugins/local_utc_crontab.py)" that uses this library to do conversions from a local AWS cron.  "L" is not supported but you can copy parts of that code to make your function or your library (and I will copy your work 🤣).
The code in all of my projects is not good, so please don't judge me.

**Comment by sirfuzzalot** [comment]
I'll check it out thanks!
